In [100]:
import pandas as pd

In [194]:
from sklearn.preprocessing import MinMaxScaler

In [63]:
from datetime import datetime
from meteostat import Point, Daily

In [185]:
cities_coordinates = {
    "Berlin": [52.5200, 13.4050],
    "Hamburg": [53.5511, 9.9937],
    "Munich": [48.1351, 11.5820],
    "Frankfurt": [50.1109, 8.6821],
    "Cologne": [50.9375, 6.9603],
    "Stuttgart": [48.7758, 9.1829],
    "Dresden": [51.0504, 13.7373],
    "Leipzig": [51.3397, 12.3731],
    "Rostock": [54.0924, 12.0991],
    "Freiburg": [47.9990, 7.8421]
}

In [186]:
wormplot_weather = pd.DataFrame()

In [187]:
start = datetime(2009, 1, 1)
end = datetime(2023, 12, 31)
weather_data = {}

In [188]:
for city in cities_coordinates:
    
   

   
    weather_data[city] = Daily(Point(cities_coordinates[city][0],cities_coordinates[city][1]), start, end)
    weather_data[city] = weather_data[city].fetch()
    weather_data[city].fillna(weather_data[city].mean(), inplace=True)
    
    weather_data[city]["city_name"] = city
    weather_data[city].reset_index(inplace=True)
    weather_data[city]['time'] = pd.to_datetime(weather_data[city]['time']) 
    weather_data[city]['day'] = weather_data[city]['time'].dt.day 
    weather_data[city]['time'] = weather_data[city]['time'].dt.to_period('M')
    weather_data[city]['time_int'] = weather_data[city]['time'].rank(method='dense').astype(int) 
    wormplot_weather = pd.concat([wormplot_weather, weather_data[city]], axis=0)

In [189]:
wormplot_weather.head(10)

,time,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name,day,time_int
0,2009-01,-2.7,-6.7,-0.8,0.1,0.0,278.0,9.7,22.7,1026.0,0.0,Berlin,1,1
1,2009-01,-2.5,-6.7,-0.3,0.7,10.0,320.0,7.9,19.1,1028.0,72.0,Berlin,2,1
2,2009-01,-4.1,-9.3,0.3,1.1,20.0,245.0,16.9,47.5,1023.2,102.0,Berlin,3,1
3,2009-01,0.6,0.0,1.0,6.0,20.0,261.0,9.4,36.0,1012.8,0.0,Berlin,4,1
4,2009-01,-5.8,-11.6,0.0,0.0,160.0,39.0,13.0,28.8,1021.1,372.0,Berlin,5,1
5,2009-01,-11.6,-17.5,-6.8,0.0,140.0,154.0,5.4,15.8,1026.9,402.0,Berlin,6,1
6,2009-01,-10.1,-18.9,-3.5,0.0,110.0,238.0,13.0,32.4,1019.2,0.0,Berlin,7,1
7,2009-01,-7.7,-10.5,-5.7,0.0,100.0,232.0,8.6,18.0,1031.0,48.0,Berlin,8,1
8,2009-01,-5.0,-9.0,-1.2,0.0,100.0,227.0,8.6,17.3,1030.2,18.0,Berlin,9,1
9,2009-01,-1.4,-5.7,-0.3,0.0,90.0,189.0,7.6,18.0,1031.5,0.0,Berlin,10,1

In [190]:
nan_count = wormplot_weather.isnull().sum().sum()
print(f'Total NaN values: {nan_count}')

Total NaN values: 0

In [191]:
wormplot_weather.to_csv("wormplot_weather.csv", index = False)

In [192]:
import shutil

In [193]:
src_file = 'wormplot_weather.csv'

# Destination directory path
dst_dir = r'D:\dev\Immersive Wormplots in VR\Dataset'

# Copy the file from source to destination
shutil.copy(src_file, dst_dir)

'D:\\dev\\Immersive Wormplots in VR\\Dataset\\wormplot_weather.csv'

In [205]:
wormplot_weather = pd.DataFrame()

In [206]:
columns_to_scale = ['tavg', 'tmin','tmax','prcp','snow','wdir','wspd','wpgt','pres','tsun']

In [207]:
start = datetime(2009, 1, 1)
end = datetime(2023, 12, 31)
weather_data = {}

In [208]:
for city in cities_coordinates:
    
   

   
    weather_data[city] = Daily(Point(cities_coordinates[city][0],cities_coordinates[city][1]), start, end)
    weather_data[city] = weather_data[city].fetch()
    weather_data[city].fillna(weather_data[city].mean(), inplace=True)
    
    # Initialize the MinMaxScaler
    scaler = MinMaxScaler()

    # Fit and transform the selected columns
    weather_data[city][columns_to_scale] = scaler.fit_transform(weather_data[city][columns_to_scale])*10

    weather_data[city]["city_name"] = city
    weather_data[city].reset_index(inplace=True)
    weather_data[city]['time'] = pd.to_datetime(weather_data[city]['time']) 
    weather_data[city]['day'] = weather_data[city]['time'].dt.day 
    weather_data[city]['time'] = weather_data[city]['time'].dt.to_period('M')
    weather_data[city]['time_int'] = weather_data[city]['time'].rank(method='dense').astype(int) 
    wormplot_weather = pd.concat([wormplot_weather, weather_data[city]], axis=0)

In [212]:
wormplot_weather.to_csv('wormplot_weather_scaled-10.csv', index = False)

In [213]:
src_file = 'wormplot_weather_scaled-10.csv'

# Destination directory path
dst_dir = r'D:\dev\Immersive Wormplots in VR\Dataset'

# Copy the file from source to destination
shutil.copy(src_file, dst_dir)

'D:\\dev\\Immersive Wormplots in VR\\Dataset\\wormplot_weather_scaled-10.csv'

In [174]:
weather_data["Munich"].head(50)

,time,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name,day,time_int
0,2009-01,-0.1,-3.5,1.4,1.2,0.0,300.0,5.8,22.0,1026.5,0.0,Munich,1,1
1,2009-01,-3.7,-5.2,-0.4,0.0,0.0,28.0,7.2,21.6,1026.5,0.0,Munich,2,1
2,2009-01,-5.6,-7.8,-3.2,0.0,0.0,104.0,7.2,22.0,1026.5,168.0,Munich,3,1
3,2009-01,-4.4,-6.1,-1.4,0.0,0.0,252.0,7.6,20.9,1021.6,336.0,Munich,4,1
4,2009-01,-4.0,-5.2,-2.9,0.0,0.0,267.0,7.2,21.2,1017.5,0.0,Munich,5,1
5,2009-01,-4.3,-5.7,-3.4,0.0,0.0,80.0,11.9,30.6,1018.5,0.0,Munich,6,1
6,2009-01,-5.4,-6.8,-4.9,0.0,0.0,32.0,5.0,15.1,1021.5,0.0,Munich,7,1
7,2009-01,-6.0,-8.1,-2.5,0.0,0.0,80.0,10.8,40.3,1028.8,288.0,Munich,8,1
8,2009-01,-8.0,-11.3,-4.2,0.0,0.0,20.0,4.7,12.2,1030.7,390.0,Munich,9,1
9,2009-01,-8.2,-12.3,-3.3,0.0,0.0,46.0,4.7,11.5,1031.3,462.0,Munich,10,1
10,2009-01,-7.7,-12.0,-0.6,0.0,0.0,349.0,3.6,11.9,1035.1,450.0,Munich,11,1
11,2009-01,-6.7,-11.9,-0.1,0.0,0.0,359.0,4.0,11.2,1030.6,462.0,Munich,12,1
12,2009-01,-4.5,-9.2,2.4,0.0,0.0,42.0,4.3,12.6,1021.3,486.0,Munich,13,1
13,2009-01,-2.8,-7.9,1.0,0.0,0.0,321.0,2.9,11.5,1017.1,0.0,Munich,14,1
14,2009-01,-0.9,-4.0,3.3,0.0,0.0,34.0,5.8,25.2,1021.5,180.0,Munich,15,1
15,2009-01,-2.8,-4.0,0.4,0.0,0.0,83.0,4.0,12.6,1026.0,162.0,Munich,16,1
16,2009-01,0.8,-5.6,8.0,0.0,0.0,246.0,5.8,23.0,1022.9,480.0,Munich,17,1
17,2009-01,3.0,-0.3,5.5,0.8,0.0,200.0,10.8,65.5,1011.1,30.0,Munich,18,1
18,2009-01,3.7,1.1,7.4,3.0,0.0,179.0,10.4,27.7,1003.7,24.0,Munich,19,1
19,2009-01,2.0,0.4,4.7,10.0,0.0,174.0,7.2,32.0,1000.6,0.0,Munich,20,1
20,2009-01,0.6,0.2,1.1,4.4,10.0,295.0,5.8,15.1,1007.9,0.0,Munich,21,1
21,2009-01,0.2,-1.9,2.9,0.0,30.0,146.0,7.2,24.5,1007.3,204.0,Munich,22,1
22,2009-01,1.2,-2.3,6.8,3.7,20.0,154.0,15.1,82.4,987.6,78.0,Munich,23,1
23,2009-01,2.0,-1.0,4.8,0.0,0.0,32.0,10.1,51.1,990.3,468.0,Munich,24,1
24,2009-01,1.2,-2.4,5.4,0.0,0.0,151.0,7.2,29.2,1000.7,360.0,Munich,25,1
25,2009-01,-0.8,-4.8,5.9,0.0,0.0,48.0,4.0,12.2,1001.7,468.0,Munich,26,1
26,2009-01,-2.6,-3.5,-1.7,0.1,0.0,306.0,6.1,18.4,1012.4,0.0,Munich,27,1
27,2009-01,-1.2,-2.1,-0.4,1.6,0.0,313.0,6.1,19.1,1017.7,0.0,Munich,28,1
28,2009-01,-1.1,-3.0,-0.1,0.0,20.0,63.0,9.0,24.1,1020.4,0.0,Munich,29,1
29,2009-01,-2.6,-3.5,-1.8,0.0,20.0,90.0,12.2,36.7,1023.3,0.0,Munich,30,1
30,2009-01,-2.6,-4.4,0.3,0.0,10.0,83.0,13.0,35.3,1018.2,192.0,Munich,31,1
31,2009-02,-2.9,-4.4,-0.7,0.0,10.0,85.0,11.2,31.3,1007.8,84.0,Munich,1,2
32,2009-02,0.3,-3.7,3.7,0.0,10.0,101.0,9.0,29.9,1002.0,6.0,Munich,2,2
33,2009-02,1.9,-1.4,7.6,0.0,10.0,359.0,4.7,14.4,998.9,318.0,Munich,3,2
34,2009-02,0.4,-3.0,6.8,0.0,0.0,185.0,4.3,13.0,999.6,492.0,Munich,4,2
35,2009-02,0.3,-3.6,6.1,0.0,0.0,68.0,5.0,23.0,1000.5,432.0,Munich,5,2
36,2009-02,-0.4,-1.3,0.8,0.0,0.0,54.0,5.8,22.3,995.0,24.0,Munich,6,2
37,2009-02,1.5,-1.9,6.2,2.0,0.0,293.0,7.9,28.8,989.2,186.0,Munich,7,2
38,2009-02,0.5,-0.8,2.8,4.5,0.0,293.0,10.4,32.8,1002.4,0.0,Munich,8,2
39,2009-02,0.9,-1.5,3.7,3.5,10.0,216.0,7.6,38.9,1010.0,276.0,Munich,9,2
40,2009-02,4.9,1.5,10.8,1.3,0.0,210.0,24.8,93.2,998.3,60.0,Munich,10,2
41,2009-02,0.1,-2.0,2.1,1.9,0.0,275.0,18.4,54.0,1011.8,72.0,Munich,11,2
42,2009-02,-1.9,-4.1,-0.6,2.5,40.0,275.0,13.0,34.6,1016.0,24.0,Munich,12,2
43,2009-02,-3.0,-4.0,-0.6,2.3,100.0,267.0,11.2,36.0,1019.4,54.0,Munich,13,2
44,2009-02,-3.0,-6.2,-0.6,0.5,120.0,275.0,10.1,25.6,1022.3,0.0,Munich,14,2
45,2009-02,-4.3,-6.5,-1.2,0.0,130.0,274.0,8.3,25.2,1029.2,306.0,Munich,15,2
46,2009-02,-1.5,-4.4,0.9,4.7,100.0,247.0,14.0,41.8,1023.2,0.0,Munich,16,2
47,2009-02,-1.3,-7.6,0.9,9.8,150.0,286.0,17.3,45.7,1017.9,0.0,Munich,17,2
48,2009-02,-7.0,-10.8,-1.8,0.0,170.0,2.0,4.7,16.6,1027.6,558.0,Munich,18,2
49,2009-02,-6.6,-10.6,-2.0,0.0,150.0,273.0,5.4,17.6,1029.0,390.0,Munich,19,2

In [176]:
weather_data["Munich"].shape

(5478, 14)

In [175]:
wormplot_weather.shape

(54780, 14)

In [138]:
weather_data.keys()

dict_keys(['Berlin', 'Hamburg', 'Munich', 'Frankfurt', 'Cologne', 'Stuttgart', 'Dresden', 'Leipzig', 'Rostock', 'Freiburg'])

In [160]:
weather_data["Berlin"].tail()

,time,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name
5473,2023-12-27,4.3,2.9,5.5,0.1,0.0,216.0,13.7,37.1,1019.7,324.0,Berlin
5474,2023-12-28,8.6,4.1,10.7,0.0,0.0,212.0,17.6,47.2,1011.7,198.0,Berlin
5475,2023-12-29,9.7,7.3,11.4,3.8,0.0,225.0,20.9,57.2,1007.1,42.0,Berlin
5476,2023-12-30,6.7,4.8,8.1,0.0,0.0,235.0,14.8,45.4,1010.8,6.0,Berlin
5477,2023-12-31,6.3,3.9,8.1,0.1,0.0,153.0,11.9,35.3,1007.4,0.0,Berlin

In [140]:
weather_data["Berlin"].shape

(5478, 11)

In [141]:
weather_data["Frankfurt"].tail()

,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name
time,,,,,,,,,,,
2023-12-27,7.1,4.8,9.5,0.0,0.0,191.0,10.3,23.4,1020.1,36.0,Frankfurt
2023-12-28,9.0,6.5,11.5,0.0,0.0,219.0,22.2,40.3,1016.9,222.0,Frankfurt
2023-12-29,10.0,9.0,11.3,0.2,0.0,225.0,26.6,55.1,1013.9,42.0,Frankfurt
2023-12-30,9.1,7.5,11.0,0.0,0.0,225.0,18.0,37.1,1015.3,108.0,Frankfurt
2023-12-31,7.0,4.4,9.4,0.9,0.0,202.0,16.4,49.7,1006.6,0.0,Frankfurt

In [142]:
weather_data["Frankfurt"].shape

(5478, 11)

In [143]:
city_data_size = []

In [144]:
for city_name in weather_data:
    city_data_size.append(weather_data[city_name].shape)

In [145]:
set(city_data_size)

{(5478, 11)}

In [146]:
weather_data["Munich"]

,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name
time,,,,,,,,,,,
2009-01-01,-0.1,-3.5,1.4,1.2,0.0,300.0,5.8,22.0,1026.5,0.0,Munich
2009-01-02,-3.7,-5.2,-0.4,0.0,0.0,28.0,7.2,21.6,1026.5,0.0,Munich
2009-01-03,-5.6,-7.8,-3.2,0.0,0.0,104.0,7.2,22.0,1026.5,168.0,Munich
2009-01-04,-4.4,-6.1,-1.4,0.0,0.0,252.0,7.6,20.9,1021.6,336.0,Munich
2009-01-05,-4.0,-5.2,-2.9,0.0,0.0,267.0,7.2,21.2,1017.5,0.0,Munich
...,...,...,...,...,...,...,...,...,...,...,...
2023-12-27,6.5,1.9,11.3,0.0,0.0,171.0,6.8,24.1,1022.1,378.0,Munich
2023-12-28,8.8,2.6,12.0,0.0,0.0,218.0,9.4,28.1,1020.1,192.0,Munich
2023-12-29,9.4,7.5,11.2,0.0,0.0,233.0,13.7,54.4,1017.6,66.0,Munich
2023-12-30,7.7,3.7,11.2,0.0,0.0,234.0,12.6,41.0,1017.9,438.0,Munich
2023-12-31,4.7,0.3,10.3,3.5,0.0,173.0,9.0,34.9,1010.6,60.0,Munich

In [147]:
 trial = weather_data["Munich"].reset_index(inplace=False)

In [148]:
weather_data["Munich"]

,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name
time,,,,,,,,,,,
2009-01-01,-0.1,-3.5,1.4,1.2,0.0,300.0,5.8,22.0,1026.5,0.0,Munich
2009-01-02,-3.7,-5.2,-0.4,0.0,0.0,28.0,7.2,21.6,1026.5,0.0,Munich
2009-01-03,-5.6,-7.8,-3.2,0.0,0.0,104.0,7.2,22.0,1026.5,168.0,Munich
2009-01-04,-4.4,-6.1,-1.4,0.0,0.0,252.0,7.6,20.9,1021.6,336.0,Munich
2009-01-05,-4.0,-5.2,-2.9,0.0,0.0,267.0,7.2,21.2,1017.5,0.0,Munich
...,...,...,...,...,...,...,...,...,...,...,...
2023-12-27,6.5,1.9,11.3,0.0,0.0,171.0,6.8,24.1,1022.1,378.0,Munich
2023-12-28,8.8,2.6,12.0,0.0,0.0,218.0,9.4,28.1,1020.1,192.0,Munich
2023-12-29,9.4,7.5,11.2,0.0,0.0,233.0,13.7,54.4,1017.6,66.0,Munich
2023-12-30,7.7,3.7,11.2,0.0,0.0,234.0,12.6,41.0,1017.9,438.0,Munich
2023-12-31,4.7,0.3,10.3,3.5,0.0,173.0,9.0,34.9,1010.6,60.0,Munich

In [149]:
trial

,time,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name
0,2009-01-01,-0.1,-3.5,1.4,1.2,0.0,300.0,5.8,22.0,1026.5,0.0,Munich
1,2009-01-02,-3.7,-5.2,-0.4,0.0,0.0,28.0,7.2,21.6,1026.5,0.0,Munich
2,2009-01-03,-5.6,-7.8,-3.2,0.0,0.0,104.0,7.2,22.0,1026.5,168.0,Munich
3,2009-01-04,-4.4,-6.1,-1.4,0.0,0.0,252.0,7.6,20.9,1021.6,336.0,Munich
4,2009-01-05,-4.0,-5.2,-2.9,0.0,0.0,267.0,7.2,21.2,1017.5,0.0,Munich
...,...,...,...,...,...,...,...,...,...,...,...,...
5473,2023-12-27,6.5,1.9,11.3,0.0,0.0,171.0,6.8,24.1,1022.1,378.0,Munich
5474,2023-12-28,8.8,2.6,12.0,0.0,0.0,218.0,9.4,28.1,1020.1,192.0,Munich
5475,2023-12-29,9.4,7.5,11.2,0.0,0.0,233.0,13.7,54.4,1017.6,66.0,Munich
5476,2023-12-30,7.7,3.7,11.2,0.0,0.0,234.0,12.6,41.0,1017.9,438.0,Munich
5477,2023-12-31,4.7,0.3,10.3,3.5,0.0,173.0,9.0,34.9,1010.6,60.0,Munich

In [107]:
trial['time'] = pd.to_datetime(trial['time'])

In [109]:
trial['day'] = trial['time'].dt.day

In [110]:
trial

,time,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name,day
0,2009-01-01,-0.1,-3.5,1.4,1.2,0.0,300.0,5.8,22.0,1026.5,0.0,Munich,1
1,2009-01-02,-3.7,-5.2,-0.4,0.0,0.0,28.0,7.2,21.6,1026.5,0.0,Munich,2
2,2009-01-03,-5.6,-7.8,-3.2,0.0,0.0,104.0,7.2,22.0,1026.5,168.0,Munich,3
3,2009-01-04,-4.4,-6.1,-1.4,0.0,0.0,252.0,7.6,20.9,1021.6,336.0,Munich,4
4,2009-01-05,-4.0,-5.2,-2.9,0.0,0.0,267.0,7.2,21.2,1017.5,0.0,Munich,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5473,2023-12-27,6.5,1.9,11.3,0.0,0.0,171.0,6.8,24.1,1022.1,378.0,Munich,27
5474,2023-12-28,8.8,2.6,12.0,0.0,0.0,218.0,9.4,28.1,1020.1,192.0,Munich,28
5475,2023-12-29,9.4,7.5,11.2,0.0,0.0,233.0,13.7,54.4,1017.6,66.0,Munich,29
5476,2023-12-30,7.7,3.7,11.2,0.0,0.0,234.0,12.6,41.0,1017.9,438.0,Munich,30
5477,2023-12-31,4.7,0.3,10.3,3.5,0.0,173.0,9.0,34.9,1010.6,60.0,Munich,31

In [111]:
trial['year_month'] = trial['time'].dt.to_period('M')

In [112]:
trial

,time,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name,day,year_month
0,2009-01-01,-0.1,-3.5,1.4,1.2,0.0,300.0,5.8,22.0,1026.5,0.0,Munich,1,2009-01
1,2009-01-02,-3.7,-5.2,-0.4,0.0,0.0,28.0,7.2,21.6,1026.5,0.0,Munich,2,2009-01
2,2009-01-03,-5.6,-7.8,-3.2,0.0,0.0,104.0,7.2,22.0,1026.5,168.0,Munich,3,2009-01
3,2009-01-04,-4.4,-6.1,-1.4,0.0,0.0,252.0,7.6,20.9,1021.6,336.0,Munich,4,2009-01
4,2009-01-05,-4.0,-5.2,-2.9,0.0,0.0,267.0,7.2,21.2,1017.5,0.0,Munich,5,2009-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5473,2023-12-27,6.5,1.9,11.3,0.0,0.0,171.0,6.8,24.1,1022.1,378.0,Munich,27,2023-12
5474,2023-12-28,8.8,2.6,12.0,0.0,0.0,218.0,9.4,28.1,1020.1,192.0,Munich,28,2023-12
5475,2023-12-29,9.4,7.5,11.2,0.0,0.0,233.0,13.7,54.4,1017.6,66.0,Munich,29,2023-12
5476,2023-12-30,7.7,3.7,11.2,0.0,0.0,234.0,12.6,41.0,1017.9,438.0,Munich,30,2023-12
5477,2023-12-31,4.7,0.3,10.3,3.5,0.0,173.0,9.0,34.9,1010.6,60.0,Munich,31,2023-12

In [113]:
# Drop the original 'time' column if no longer needed
trial = trial.drop(columns=['time'])

# Rename 'year_month' to 'time' if desired
trial = trial.rename(columns={'year_month': 'time'})

In [114]:
trial

,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name,day,time
0,-0.1,-3.5,1.4,1.2,0.0,300.0,5.8,22.0,1026.5,0.0,Munich,1,2009-01
1,-3.7,-5.2,-0.4,0.0,0.0,28.0,7.2,21.6,1026.5,0.0,Munich,2,2009-01
2,-5.6,-7.8,-3.2,0.0,0.0,104.0,7.2,22.0,1026.5,168.0,Munich,3,2009-01
3,-4.4,-6.1,-1.4,0.0,0.0,252.0,7.6,20.9,1021.6,336.0,Munich,4,2009-01
4,-4.0,-5.2,-2.9,0.0,0.0,267.0,7.2,21.2,1017.5,0.0,Munich,5,2009-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5473,6.5,1.9,11.3,0.0,0.0,171.0,6.8,24.1,1022.1,378.0,Munich,27,2023-12
5474,8.8,2.6,12.0,0.0,0.0,218.0,9.4,28.1,1020.1,192.0,Munich,28,2023-12
5475,9.4,7.5,11.2,0.0,0.0,233.0,13.7,54.4,1017.6,66.0,Munich,29,2023-12
5476,7.7,3.7,11.2,0.0,0.0,234.0,12.6,41.0,1017.9,438.0,Munich,30,2023-12
5477,4.7,0.3,10.3,3.5,0.0,173.0,9.0,34.9,1010.6,60.0,Munich,31,2023-12

In [117]:
trial['time_int'] = trial['time'].rank(method='dense').astype(int) - 1

In [118]:
trial

,tavg,tmin,tmax,prcp,snow,wdir,wspd,wpgt,pres,tsun,city_name,day,time,time_int
0,-0.1,-3.5,1.4,1.2,0.0,300.0,5.8,22.0,1026.5,0.0,Munich,1,2009-01,0
1,-3.7,-5.2,-0.4,0.0,0.0,28.0,7.2,21.6,1026.5,0.0,Munich,2,2009-01,0
2,-5.6,-7.8,-3.2,0.0,0.0,104.0,7.2,22.0,1026.5,168.0,Munich,3,2009-01,0
3,-4.4,-6.1,-1.4,0.0,0.0,252.0,7.6,20.9,1021.6,336.0,Munich,4,2009-01,0
4,-4.0,-5.2,-2.9,0.0,0.0,267.0,7.2,21.2,1017.5,0.0,Munich,5,2009-01,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5473,6.5,1.9,11.3,0.0,0.0,171.0,6.8,24.1,1022.1,378.0,Munich,27,2023-12,179
5474,8.8,2.6,12.0,0.0,0.0,218.0,9.4,28.1,1020.1,192.0,Munich,28,2023-12,179
5475,9.4,7.5,11.2,0.0,0.0,233.0,13.7,54.4,1017.6,66.0,Munich,29,2023-12,179
5476,7.7,3.7,11.2,0.0,0.0,234.0,12.6,41.0,1017.9,438.0,Munich,30,2023-12,179
5477,4.7,0.3,10.3,3.5,0.0,173.0,9.0,34.9,1010.6,60.0,Munich,31,2023-12,179

0         0
1         0
2         0
3         0
4         0
       ...
5473    179
5474    179
5475    179
5476    179
5477    179
Name: time_int, Length: 5478, dtype: int32

In [116]:
trial.to_csv("sample.csv", index = False)